version: '3.7'

services:
  web:
    container_name: neurumTest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    restart: always
    environment:
      - NODE_ENV=production
